version: "3"

services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.93.0
    ports:
      - "8889:8889"
    environment:
      - METRICS_HOST=fake-metrics
      - METRICS_PORT=5000
      - PROMETHEUS_PORT=8889
    volumes:
      - ./config/collector/config.yml:/etc/otelcol-contrib/config.yaml:ro
      - ./logs:/var/logs

  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.1.5
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:2.9.4
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
