receivers:
  filelog/file1:
    include: [ "/var/logs/generated.log" ]
    operators:
      - type: json_parser
        parse_from: body
        timestamp:
          parse_from: attributes.timeMillis
          layout_type: epoch
          layout: ms
          # parse_from: attributes.timestamp
          # layout: "%Y-%m-%dT%H:%M:%S.%f%z"
        severity:
          parse_from: attributes.level
          mapping:
            error: ERROR
            warn: WARN
            info: INFO
            debug: DEBUG
      - type: move
        from: attributes.message
        to: body.message
  filelog/file2:
    include: [ "/var/logs/generated2.log" ]
    operators:
      - type: json_parser
        parse_from: body
        timestamp:
          parse_from: body.timeMillis
          layout_type: epoch
          layout: ms
          # parse_from: attributes.timestamp
          # layout: "%Y-%m-%dT%H:%M:%S.%f%z"
        severity:
          parse_from: body.level
          mapping:
            error: ERROR
            warn: WARN
            info: INFO
            debug: DEBUG
        parse_to: body

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  resource: 
    attributes:  
      - action: insert 
        key: thread_id 
        from_attribute: attributes.threadId
      - action: insert 
        key: loki.resource.labels 
        value: thread_id

exporters:
  prometheus:
    endpoint: ":${env:PROMETHEUS_PORT}"
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

service:
  telemetry:
    logs:
  pipelines:
    logs:
      receivers: [ "filelog/file1", "filelog/file2" ]
      processors: [ "resource"]
      exporters: [ "loki" ]
    metrics:
      receivers: [ "prometheus" ]
      processors: [ "batch"]
      exporters: [ "prometheus" ]
